name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: write # Allow actions to write back to the repository

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Cache Yarn dependencies
      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v4
        with:
          node-version: 18.19.1
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      # Run Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome

      - name: Run Tests for e2e
        run: yarn test:e2e:headless
